# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="blinks"

# Example aliases
alias zshconfig="vim ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias rmd="rm -rf"
alias c="xclip -sel clip"
alias v="xclip -sel clip -o"
alias sserver="ruby -run -e httpd . -p 5000"
alias zshreload=". ~/.zshrc"
alias gA="git add -A"
mkchdir() {
  mkdir $1 && cd $1;
}
# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"
unsetopt correct
unsetopt correct_all
# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#source /home/xaro/.oh-my-zsh/custom/plugins/antigen/antigen.zsh
#antigen use oh-my-zsh
#antigen bundle zsh-users/zsh-syntax-highlighting
#antigen bundle zsh-users/zsh-history-substring-search
#antigen apply

zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey "^[e" end-of-line
bindkey "^[a" beginning-of-line
bindkey "[D" backward-word
bindkey "[C" forward-word

plugins=(git ruby rails heroku)
#fpath=(/home/xaro/.oh-my-zsh/custom/plugins/zsh-completions/src $fpath)

source $ZSH/oh-my-zsh.sh
source ~/.profile

export PATH="/Users/xaro/.rvm/gems/ruby-2.1.1/bin:/Users/xaro/.rvm/gems/ruby-2.1.1@global/bin:/Users/xaro/.rvm/rubies/ruby-2.1.1/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/xaro/.rvm/bin"
